### ISSUE TITLE
Chat Box System (Feature)

### ISSUE THREAD

**Issue by Alicat42** [Virtual-World-Crunchers/GamingForThePeople#2]
This feature is about incorporating a the chat box system to the game. Once the user begins the game, the chat box will appear on the screen that they can type into throughout gameplay. The Shooter Game that is being used already has a chat feature implemented, but it is a simple white box that the player can input messages in which its visibility is toggled by pressing 'C'. The interface is shown in the image below:

![Screenshot (138)](https://user-images.githubusercontent.com/89177995/135868717-a2d320d6-a587-445c-ad47-dbab6d926c1e.png)

The aim of this feature is to get toxic messages to display to the user during gameplay and to allow the user to also type messages.

## Dependencies
How this gets implemented will depend on what is already in the code for the Shooter Game.

## Tasks

- [x] Temporarily show recent messages from chat
- [x] Display random toxic messages in chat (#3)
- [x] Trigger toxic messages at certain gameplay events (eg. killing a player, player killing the user, etc.)

**Comment by Alicat42** [comment]
Here's a screenshot of the toxic messages showing when a player/bot dies:

![Screenshot (146)](https://user-images.githubusercontent.com/89177995/136659967-a4da10d0-3e0e-42db-8a29-f58a356c4a74.png)

**Comment by Alicat42** [comment]
Something to keep an eye on is whether or not multiple messages appear at once if more than 1 human player is in the game. (eg. if there are 2 human players, then 2 toxic messages are played since the event is triggering on two instances of the game).
