### ISSUE TITLE
Toxic Chat Entries (Task)

### ISSUE THREAD

**Issue by Alicat42** [Virtual-World-Crunchers/GamingForThePeople#3]
The purpose of this task is to create a class of functions that will store and use a set of strings of toxic chat input to be sudo-randomly triggered on certain events (eg. when a player is killed, when a bot is killed, etc).  This is an extension of #2.

## ToDos
- [x] Create a new class for toxic chat functions
- [x] Create a string array
- [x] Enter strings of toxic chat samples into array
- [x] Create function to get a random string from array
- [x] Add function call from this class to the code that is triggered when the player or a bot dies.
- [x] Using the string returned from the function call, send it to the chat.
