### ISSUE TITLE
Toxic Chat Mitigation (Feature)

### ISSUE THREAD

**Issue by Alicat42** [Virtual-World-Crunchers/GamingForThePeople#4]
This feature is about applying the filters and slow chat that will help mitigate the toxic chat. This will be the key feature that will test whether or not the project is effective in mitigating toxicity for online solo players. 

## Dependencies
Items 2 and 4 depends on what is implemented for #2.

## Tasks
- [ ] #6
- [x] Implement slow chat
- [ ] Create a C++ file containing common examples of toxic chat and inappropriate language
- [ ] Implement a filter to recognise and change/omit toxic chat
