### ISSUE TITLE
Design Process Page (Wiki)

### ISSUE THREAD

**Issue by Alicat42** [Virtual-World-Crunchers/GamingForThePeople#5]
This wiki page will provide an overview of the design process undertaken throughout the project. This is one of the documentation requirements for the assessment. The suggested outline is as follows:

- Conference poster & Promotional Material: link to this up front so we see it first.
- Link to the prototype, and instructions for how to deploy and use it, including any login credentials.
- Summary: what is the problem/opportunity space and how did you (aka. us) address it?
- Process: how did you tackle this problem? Use images and extended captions to explain the design process and how your ideas evolved. Mention any limitations and relevant theory.
- Include a list of who did what in the project.
- Aim for no more than 1000 words plus images. References not included in count. Reference in any style, but be consistent.

## ToDos
- [x] Link to Conference poster
- [x] Link to Promotional Material
- [ ] Link to Prototype
- [ ] Instructions on how to use the prototype
- [ ] Summary (the problem domain/space and how we addressed it)
- [ ] Process (how we tackled the problem)
- [ ] List of what each of us did in the project
- [ ] References

**Comment by RileyHen** [comment]
Conference Poster complete
