### ISSUE TITLE
Provide a toggle buttons for player to choose what to use (eg. slow chat, toxicity filters, etc.)

### ISSUE THREAD

**Issue by Alicat42** [Virtual-World-Crunchers/GamingForThePeople#6]
This task will provide users with buttons to the enable toxic chat to be mitigated. This includes disabling/enabling the slow chat, profanity filter, and message switch, etc.

## ToDos

- [ ]  Slow Chat Button
- [ ]  Profanity Filter Button
- [ ]  Message Switch Button
- [ ]  Toxicity Notification Button??

**Comment by Alicat42** [comment]
The slow chat and filter buttons have toggle actions, but are not visual buttons that the player can interact with. To toggle Slow Chat, press Alt+1; and to toggle Filter Chat, press Alt+2.
